CarShop/config/routes.rb
Rails.application.routes.draw do
  resources :salesman_quotes

  resources :car_stocks

  resources :finance_reports

  resources :homepages

  resources :sale_people

  resources :quotes

  resources :loans

  resources :customers

  resources :cars

  get 'homepages/index'

    root 'homepages#index'

end

CarShop/app/models/salesman_quote.rb
class SalesmanQuote < ActiveRecord::Base


end

CarShop/app/controllers/salesman_quotes_controller.rb
class SalesmanQuotesController < ApplicationController
  def index
    @quotes = Quote.all
  end
end

CarShop/app/helpers/salesman_quotes_helper.rb
module SalesmanQuotesHelper
end

CarShop/app/views/salesman_quotes/index.html.erb
<%- model_class = Quote -%>


<h1> Sales Personnel specific quotes</h1>
<br>

<%= form_tag(quotes_path, :method => "get", id: "search_customer") do %>
    List of salemen <%= collection_select :get ,:customers_id , Customer.all ,:id ,:name %>
    <%= text_field_tag :search, params[:search], placeholder: "Type saleman's name " %>
    <%= submit_tag "Find" %>
<% end %>

<table class="table table-striped">
  <thead>
  <tr>

    <th><%= model_class.human_attribute_name(:sale_person_id) %></th>
    <th><%= model_class.human_attribute_name(:customer_id) %></th>
    <th><%= model_class.human_attribute_name(:car_id) %></th>
    <th><%= model_class.human_attribute_name(:car_price) %></th>
    <th><%= model_class.human_attribute_name(:sale_tax) %></th>
    <th><%= model_class.human_attribute_name(:total_price) %></th>
    <th><%= model_class.human_attribute_name(:quote_status) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @quotes.each do |quote| %>
      <tr>

        <td><%= quote.sale_person.name%></td>
        <td><%= quote.customer.name %></td>
        <td><%= quote.car.model %></td>
        <td><%= number_to_currency(quote.car_price) %></td>
        <td><%= number_to_currency(quote.sale_tax) %></td>
        <td><%=number_to_currency(quote.total_price) %></td>
        <td><%= quote.update_status %></td>
        <td><%=l quote.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_quote_path(quote), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      quote_path(quote),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>