CarShop/config/routes.rb
Rails.application.routes.draw do
  resources :salesman_quotes

  resources :car_stocks

  resources :finance_reports

  resources :homepages

  resources :sale_people

  resources :quotes

  resources :loans

  resources :customers

  resources :cars

  get 'homepages/index'

    root 'homepages#index'

end

CarShop/app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :quotes
  validates :name ,presence: true

  def self.searchable_columns
    wanted_columns = ['name', 'address', 'phone' ]
    self.column_names.select{ |column| wanted_columns.include?(column) }
  end


  def self.translated_searchable_columns
    columns = self.searchable_columns
    result = columns.map{ |column| [Customer.human_attribute_name(column.to_sym), column] }
    result
  end


  def self.search(keyword,column_name)
    if self.column_names.include?(column_name.to_s)
      where("customers.#{column_name} LIKE ?", "%#{keyword}%")
    else
      self.all
    end
  end
end

CarShop/app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index

    if params[:search]
      @customers = Customer.search(params[:search],params[:search_column]).paginate(:page => params[:page], :per_page => 10)
    else
      @customers = Customer.all.paginate(:page => params[:page], :per_page => 10)
    end
  end


  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def customer_params
    params.require(:customer).permit(:name, :address, :city, :state, :zip, :phone, :email)
  end
end

CarShop/app/helpers/customers_helper.rb
module CustomersHelper
end

CarShop/app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => "form-horizontal customer" } do |f| %>

    <% if @customer.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @customer.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="control-group">
      <%= f.label :name, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :name, :class => 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :address, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :address, :class => 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :city, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :city, :class => 'form-control' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :state, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :state, :class => 'form-control' %>
    </div>
      <div class="control-group">
        <%= f.label :zip, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :zip, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
      <%= f.label :phone, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :phone, :class => 'form-control' %>
      </div>
    </div>
      <div class="control-group">
        <%= f.label :email, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :email, :class => 'form-control' %>
        </div>
      </div>
  </div>


      <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn btn-default' %>

<%end%>

CarShop/app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.Customer Management', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

CarShop/app/views/customers/index.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.Customer Management', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>


<%= form_tag(customers_path, :method => "get", id: "search_customer") do %>
    Search by <%= select_tag :search_column, options_for_select(Customer.translated_searchable_columns, params[:search_column]) %>
    <%= text_field_tag :search, params[:search], placeholder: "Search customer" %>
    <%= submit_tag "Search" %>
<% end %>




<br>

<%= will_paginate @customers %>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:address) %></th>
    <th><%= model_class.human_attribute_name(:city) %></th>
    <th><%= model_class.human_attribute_name(:state) %></th>
    <th><%= model_class.human_attribute_name(:zip) %></th>
    <th><%= model_class.human_attribute_name(:phone) %></th>
    <th><%= model_class.human_attribute_name(:email) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @customers.each do |customer| %>
      <tr>
        <td><%= link_to customer.id, customer_path(customer) %></td>
        <td><%= customer.name %></td>
        <td><%= customer.address %></td>
        <td><%= customer.city %></td>
        <td><%= customer.state %></td>
        <td><%= customer.zip %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%=l customer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_customer_path(customer), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_path(customer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_customer_path,
            :class => 'btn btn-primary' %>

CarShop/app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.Customer Management', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

CarShop/app/views/customers/show.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.Customer Management', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @customer.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:address) %>:</strong></dt>
  <dd><%= @customer.address %></dd>
  <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
  <dd><%= @customer.city %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @customer.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
  <dd><%= @customer.zip %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone) %>:</strong></dt>
  <dd><%= @customer.phone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @customer.email %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
            customers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
            edit_customer_path(@customer), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
            customer_path(@customer),
            :method => 'delete',
            :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
            :class => 'btn btn-danger' %>