CarShop/config/routes.rb
Rails.application.routes.draw do
  resources :salesman_quotes

  resources :car_stocks

  resources :finance_reports

  resources :homepages

  resources :sale_people

  resources :quotes

  resources :loans

  resources :customers

  resources :cars

  get 'homepages/index'

    root 'homepages#index'

end

CarShop/app/models/car_stock.rb
class CarStock < ActiveRecord::Base
end

CarShop/app/controllers/car_stocks_controller.rb
class CarStocksController < ApplicationController

  def index

    if params[:search]
      @cars = Car.search_car(params[:search],params[:search_column]).paginate(:page => params[:page], :per_page => 10)
    else
      @cars = Car.all.paginate(:page => params[:page], :per_page => 10)
    end
  end

end

CarShop/app/helpers/car_stocks_helper.rb
module CarStocksHelper
end

CarShop/app/views/car_stocks/index.html.erb
<%- model_class = Car -%>
<div class="page-header">
  <h1>CAR STOCK</h1>
</div>

<%= will_paginate @cars %>

<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:model) %></th>
    <th><%= model_class.human_attribute_name(:make) %></th>
    <th><%= model_class.human_attribute_name(:color) %></th>
    <th><%= model_class.human_attribute_name(:year) %></th>
    <th><%= model_class.human_attribute_name(:vin) %></th>
    <th><%= model_class.human_attribute_name(:price) %></th>
    <th><%= model_class.human_attribute_name(:car_status) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= link_to car.id, car_path(car) %></td>
        <td><%= car.model %></td>
        <td><%= car.make %></td>
        <td><%= car.color %></td>
        <td><%= car.year %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.price) %></td>
        <td><%= car.car_update_status %></td>
        <td><%=l car.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_car_path(car), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      car_path(car),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car stock', new_car_stock_path %>